theme: jekyll-theme-minimal
title: Reddit Snowball Effect
description: A simple Jekyll website template for ADA projects.
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Test
    url: page
  - title: Example
    url: example
